# Utilisez l'image officielle Python comme base
FROM python:3.9-slim

RUN apt-get update && apt-get install -y iputils-ping

# Copiez le code de votre application Tkinter dans le conteneur
COPY Programs/interface.py /app/interface.py

# Définissez le répertoire de travail
WORKDIR /app

# Installez les dépendances nécessaires pour Tkinter
RUN apt-get update && apt-get install -y python3-tk

# Copiez le fichier des dépendances Python
COPY requirements.txt /app/requirements.txt

# Installez les dépendances Python
RUN pip --no-cache-dir install -r requirements.txt

# Exécutez l'application lors du démarrage du conteneur
CMD ["python3", "interface.py"]
